setwd('C:\\Users\\britt\\OneDrive\\BIOL 461')
hawaii01 <- read.csv('C:/Users/britt/OneDrive/BIOL 461/hawaii data no.csv')
hawaii02 <- read.csv('C:/Users/britt/OneDrive/BIOL 461/hawaii data y.csv')
miami01 <- read.csv('C:/Users/britt/OneDrive/BIOL 461/miami data no.csv')
miami02 <- read.csv('C:/Users/britt/OneDrive/BIOL 461/miami data y.csv')

par(mfrow=c(1,2), mar=c(4,4,1,1), las=1)
plot(hawaii01$Monarch, hawaii01$Longevity, pch=16, xlab="monarch", ylab="longevity")
title(main="Uninfected Monarchs: Hawaii")
plot(hawaii02$Monarch, hawaii02$Longevity, pch=16, xlab="monarch", ylab="longevity")
title(main="Infected Monarchs: Hawaii")
plot(miami01$Monarch, miami01$Longevity, pch=16, xlab="monarch", ylab="longevity")
title(main="Uninfected Monarchs: Miami")
plot(miami02$Monarch, miami02$Longevity, pch=16, xlab="monarch", ylab="longevity")
title(main="Infected Monarchs: Miami")
miami001 <- read.csv('C:/Users/britt/OneDrive/BIOL 461/miami001.csv')
hawaii001 <- read.csv('C:/Users/britt/OneDrive/BIOL 461/hawaii001.csv')
par(mfrow=c(1,2), mar=c(4,4,1,1), las=1)
plot(hawaii001$Monarch, hawaii001$Longevity, pch=16, xlab="monarch", ylab="longevity")
title(main="All Monarchs: Hawaii")
plot(miami001$Monarch, miami001$Longevity, pch=16, xlab="monarch", ylab="longevity")
title(main="All Monarchs: Miami")
